version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  #post_build:
   # commands:
     # - aws cloudfront create-invalidation --distribution-id E3VX7OWV33MSBC --paths "/*"

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
